name: docs-build

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm install

      - name: Permission Grant
        run: chmod +x ./build.sh
      # 运行构建脚本
      - name: Build VuePress site
        run: ./build.sh

      - name: Commit report
        run: |
          git config --global user.name 'vran-dev'
          git config --global user.email 'vran_dev@foxmail.com'
          git commit -am "deploy pages"
          git push